apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: spaceinvader-pipelinerun-
spec:
  serviceAccountName: docker-login
  pipelineRef:
    name: spaceinvader-pipeline
  params:
    - name: IMAGE
      value: docker.io/cloudacademydevops/spaceinvader
    - name: TAG
      value: latest
  workspaces:
    - name: linked-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi