apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels: 
        app: nodejs-app
    spec:
      containers: 
      - name: nodejs-app 
        image: cloudacademydevops/nodejs-app:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  labels:
    env: demo
spec:
  ports:
   - protocol: TCP
     port: 80
     targetPort: 8081
  selector:
    app: nodejs-app
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: nodejs
  labels:
    env: demo
spec:
  to:
    kind: Service
    name: nodejs-service
    weight: 100
  port:
    targetPort: 8081
  wildcardPolicy: None
